// This file is auto-generated by @hey-api/openapi-ts

export type AdjustedTeamMetrics = {
    year: number;
    teamId: number;
    team: string;
    conference: string;
    epa: {
        rushing: number;
        passing: number;
        total: number;
    };
    epaAllowed: {
        rushing: number;
        passing: number;
        total: number;
    };
    successRate: {
        passingDowns: number;
        standardDowns: number;
        total: number;
    };
    successRateAllowed: {
        passingDowns: number;
        standardDowns: number;
        total: number;
    };
    rushing: {
        highlightYards: number;
        openFieldYards: number;
        secondLevelYards: number;
        lineYards: number;
    };
    rushingAllowed: {
        highlightYards: number;
        openFieldYards: number;
        secondLevelYards: number;
        lineYards: number;
    };
    explosiveness: number;
    explosivenessAllowed: number;
};

export type AdvancedBoxScore = {
    gameInfo: {
        excitement: number;
        homeWinner: boolean;
        awayWinProb: number;
        awayPoints: number;
        awayTeam: string;
        homeWinProb: number;
        homePoints: number;
        homeTeam: string;
    };
    teams: {
        fieldPosition: Array<TeamFieldPosition>;
        scoringOpportunities: Array<TeamScoringOpportunities>;
        havoc: Array<TeamHavoc>;
        rushing: Array<TeamRushingStats>;
        explosiveness: Array<TeamExplosiveness>;
        successRates: Array<TeamSuccessRates>;
        cumulativePpa: Array<TeamPPA>;
        ppa: Array<TeamPPA>;
    };
    players: {
        ppa: Array<PlayerPPA>;
        usage: Array<PlayerGameUsage>;
    };
};

export type AdvancedGameStat = {
    gameId: number;
    season: number;
    seasonType: SeasonTypeDB;
    week: number;
    team: string;
    opponent: string;
    offense: {
        passingPlays: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
        };
        rushingPlays: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
        };
        passingDowns: {
            explosiveness: (number) | null;
            successRate: number;
            ppa: number;
        };
        standardDowns: {
            explosiveness: (number) | null;
            successRate: number;
            ppa: number;
        };
        openFieldYardsTotal: number;
        openFieldYards: (number) | null;
        secondLevelYardsTotal: number;
        secondLevelYards: number;
        lineYardsTotal: number;
        lineYards: number;
        stuffRate: number;
        powerSuccess: (number) | null;
        explosiveness: (number) | null;
        successRate: number;
        totalPPA: number;
        ppa: number;
        drives: number;
        plays: number;
    };
    defense: {
        passingPlays: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
        };
        rushingPlays: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
        };
        passingDowns: {
            explosiveness: (number) | null;
            successRate: number;
            ppa: number;
        };
        standardDowns: {
            explosiveness: (number) | null;
            successRate: number;
            ppa: number;
        };
        openFieldYardsTotal: (number) | null;
        openFieldYards: number;
        secondLevelYardsTotal: number;
        secondLevelYards: number;
        lineYardsTotal: number;
        lineYards: number;
        stuffRate: number;
        powerSuccess: (number) | null;
        explosiveness: number;
        successRate: number;
        totalPPA: number;
        ppa: number;
        drives: number;
        plays: number;
    };
};

export type AdvancedSeasonStat = {
    season: number;
    team: string;
    conference: string;
    offense: {
        passingPlays: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
            rate: number;
        };
        rushingPlays: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
            rate: number;
        };
        passingDowns: {
            explosiveness: (number) | null;
            successRate: number;
            ppa: number;
            rate: number;
        };
        standardDowns: {
            explosiveness: (number) | null;
            successRate: number;
            ppa: number;
            rate: number;
        };
        havoc: {
            db: (number) | null;
            frontSeven: (number) | null;
            total: (number) | null;
        };
        fieldPosition: {
            averagePredictedPoints: (number) | null;
            averageStart: (number) | null;
        };
        pointsPerOpportunity: number;
        totalOpportunies: number;
        openFieldYardsTotal: number;
        openFieldYards: number;
        secondLevelYardsTotal: number;
        secondLevelYards: number;
        lineYardsTotal: number;
        lineYards: number;
        stuffRate: number;
        powerSuccess: (number) | null;
        explosiveness: (number) | null;
        successRate: number;
        totalPPA: number;
        ppa: number;
        drives: number;
        plays: number;
    };
    defense: {
        passingPlays: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
            rate: number;
        };
        rushingPlays: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
            rate: number;
        };
        passingDowns: {
            explosiveness: (number) | null;
            successRate: number;
            totalPPA: number;
            ppa: number;
            rate: number;
        };
        standardDowns: {
            explosiveness: (number) | null;
            successRate: number;
            ppa: number;
            rate: number;
        };
        havoc: {
            db: (number) | null;
            frontSeven: (number) | null;
            total: (number) | null;
        };
        fieldPosition: {
            averagePredictedPoints: (number) | null;
            averageStart: (number) | null;
        };
        pointsPerOpportunity: number;
        totalOpportunies: number;
        openFieldYardsTotal: number;
        openFieldYards: number;
        secondLevelYardsTotal: number;
        secondLevelYards: number;
        lineYardsTotal: number;
        lineYards: number;
        stuffRate: number;
        powerSuccess: (number) | null;
        explosiveness: (number) | null;
        successRate: number;
        totalPPA: number;
        ppa: number;
        drives: number;
        plays: number;
    };
};

export type AggregatedTeamRecruiting = {
    team: string;
    conference: string;
    positionGroup: (string) | null;
    averageRating: number;
    totalRating: number;
    commits: number;
    averageStars: number;
};

export type BettingGame = {
    id: number;
    season: number;
    seasonType: SeasonType;
    week: number;
    startDate: string;
    homeTeamId: number;
    homeTeam: string;
    homeConference: (string) | null;
    homeClassification: ((DivisionClassification) | null);
    homeScore: (number) | null;
    awayTeamId: number;
    awayTeam: string;
    awayConference: (string) | null;
    awayClassification: ((DivisionClassification) | null);
    awayScore: (number) | null;
    lines: Array<GameLine>;
};

export type CalendarWeek = {
    season: number;
    week: number;
    seasonType: SeasonType;
    startDate: string;
    endDate: string;
    /**
     * @deprecated
     */
    firstGameStart: string;
    /**
     * @deprecated
     */
    lastGameStart: string;
};

export type CfpCoachSeasonOutcome = 'active' | 'eliminated' | 'champion';

export type CfpPlayoff = {
    season: number;
    competition: PlayoffCompetition_Cfp;
    format: string;
    teamCount: number;
    status: PlayoffStatus;
    participants: Array<PlayoffParticipant>;
    rounds: Array<PlayoffRoundRecord>;
    champion: ((PlayoffTeam) | null);
};

export type CfpPlayoffNotFound = {
    message: 'CFP playoff not found';
};

export type message = 'CFP playoff not found';

export type Coach = {
    id: number;
    firstName: string;
    lastName: string;
    /**
     * @deprecated
     */
    hireDate: (string) | null;
    seasons: Array<CoachSeason>;
};

export type CoachAlmaMater = {
    id: number;
    school: string;
};

export type CoachCareer = {
    games: number;
    wins: number;
    losses: number;
    ties: number;
    winPercentage: (number) | null;
    seasons: number;
    teams: number;
    firstYear: number;
    lastYear: number;
};

export type CoachCfpContext = {
    appeared: boolean;
    seed: (number) | null;
    outcome: ((CfpCoachSeasonOutcome) | null);
};

export type CoachDraftContext = {
    year: number;
    totalPicks: number;
    firstRoundPicks: number;
};

export type CoachNotFound = {
    message: 'Coach not found';
};

export type message2 = 'Coach not found';

export type CoachPollResume = {
    preseasonRank: (number) | null;
    postseasonRank: (number) | null;
    bestRank: (number) | null;
    weeksRanked: number;
    weeksTopTen: number;
};

export type CoachProfile = {
    id: number;
    firstName: string;
    lastName: string;
    displayName: (string) | null;
    currentTeam: ((CoachSeasonTeamReference) | null);
    career: CoachCareer;
    birthDate: (string) | null;
    almaMater: ((CoachAlmaMater) | null);
    graduationYear: (number) | null;
    wikidataId: (string) | null;
    hallOfFameYear: (number) | null;
};

export type CoachRatingContext = {
    spSpecialTeams: (number) | null;
    strengthOfSchedule: (number) | null;
    secondOrderWins: (number) | null;
    fpi: (number) | null;
    yearOverYear: {
        spOverall: (number) | null;
        srs: (number) | null;
        wins: (number) | null;
    };
};

export type CoachRecord = {
    games: number;
    wins: number;
    losses: number;
    ties: number;
    winPercentage: (number) | null;
};

export type CoachRecordSplits = {
    conference: CoachRecord;
    postseason: CoachRecord;
    home: CoachRecord;
    away: CoachRecord;
    neutral: CoachRecord;
};

export type CoachRecruitingContext = {
    rank: (number) | null;
    points: (number) | null;
    talent: (number) | null;
};

export type CoachReference = {
    id: number;
    firstName: string;
    lastName: string;
};

export type CoachScoring = {
    pointsFor: number;
    pointsAgainst: number;
    averagePointDifferential: (number) | null;
};

export type CoachSeason = {
    teamId: number;
    school: string;
    conference: (string) | null;
    year: number;
    games: number;
    wins: number;
    losses: number;
    ties: number;
    winPercentage: (number) | null;
    preseasonRank: (number) | null;
    postseasonRank: (number) | null;
    srs: (number) | null;
    spOverall: (number) | null;
    spOffense: (number) | null;
    spDefense: (number) | null;
};

export type CoachSeasonTeamReference = {
    id: number;
    school: string;
    conference: (string) | null;
};

export type CoachTeamReference = {
    id: number;
    school: string;
};

export type CoachTenure = {
    id: number;
    coach: CoachReference;
    team: CoachTeamReference;
    hireDate: (string) | null;
    startYear: number;
    endYear: (number) | null;
    effectiveStart: (string) | null;
    effectiveEnd: (string) | null;
    isInterim: boolean;
    active: boolean;
    seasons: number;
    record: CoachRecord;
    attributionComplete: boolean;
};

export type Conference = {
    id: number;
    name: string;
    shortName: (string) | null;
    abbreviation: (string) | null;
    classification: ((ConferenceClassification) | null);
    memberCount: number;
};

export type ConferenceClassification = 'fbs' | 'fcs' | 'ii' | 'ii/iii' | 'iii';

export type ConferenceSP = {
    year: number;
    conference: string;
    rating: number;
    secondOrderWins: (number) | null;
    sos: (number) | null;
    offense: {
        pace: (number) | null;
        runRate: (number) | null;
        passingDowns: (number) | null;
        standardDowns: (number) | null;
        passing: (number) | null;
        rushing: (number) | null;
        explosiveness: (number) | null;
        success: (number) | null;
        rating: number;
    };
    defense: {
        havoc: {
            db: (number) | null;
            frontSeven: (number) | null;
            total: (number) | null;
        };
        passingDowns: (number) | null;
        standardDowns: (number) | null;
        passing: (number) | null;
        rushing: (number) | null;
        explosiveness: (number) | null;
        success: (number) | null;
        rating: number;
    };
    specialTeams: {
        rating: (number) | null;
    };
};

export type CoreRatingSeasonType = 'regular' | 'postseason';

export type DetailedCoachSeason = {
    games: number;
    wins: number;
    losses: number;
    ties: number;
    winPercentage: (number) | null;
    coach: CoachReference;
    team: CoachSeasonTeamReference;
    year: number;
    preseasonRank: (number) | null;
    postseasonRank: (number) | null;
    srs: (number) | null;
    spOverall: (number) | null;
    spOffense: (number) | null;
    spDefense: (number) | null;
    teamMetrics: CoachRatingContext;
    recruiting: CoachRecruitingContext;
    pollResume: ((CoachPollResume) | null);
    attributionComplete: boolean;
    recordSplits: ((CoachRecordSplits) | null);
    scoring: ((CoachScoring) | null);
    cfp: CoachCfpContext;
    draftFollowingSeason: ((CoachDraftContext) | null);
};

export type DivisionClassification = 'fbs' | 'fcs' | 'ii' | 'iii';

export type DraftPick = {
    collegeAthleteId: (number) | null;
    nflAthleteId: number;
    collegeId: number;
    collegeTeam: string;
    collegeConference: (string) | null;
    nflTeamId: number;
    nflTeam: string;
    year: number;
    overall: number;
    round: number;
    pick: number;
    name: string;
    position: string;
    height: (number) | null;
    weight: (number) | null;
    preDraftRanking: (number) | null;
    preDraftPositionRanking: (number) | null;
    preDraftGrade: (number) | null;
    hometownInfo: {
        countyFips: (string) | null;
        longitude: (string) | null;
        latitude: (string) | null;
        country: (string) | null;
        state: (string) | null;
        city: (string) | null;
    };
};

export type DraftPosition = {
    name: string;
    abbreviation: string;
};

export type DraftTeam = {
    location: string;
    nickname: (string) | null;
    displayName: (string) | null;
    logo: (string) | null;
};

export type Drive = {
    offense: string;
    offenseConference: (string) | null;
    defense: string;
    defenseConference: (string) | null;
    gameId: number;
    id: string;
    driveNumber: (number) | null;
    scoring: boolean;
    startPeriod: number;
    startYardline: number;
    startYardsToGoal: number;
    startTime: {
        seconds: (number) | null;
        minutes: (number) | null;
    };
    endPeriod: number;
    endYardline: number;
    endYardsToGoal: number;
    endTime: {
        seconds: (number) | null;
        minutes: (number) | null;
    };
    elapsed: {
        seconds: (number) | null;
        minutes: (number) | null;
    };
    plays: number;
    yards: number;
    driveResult: string;
    isHomeOffense: boolean;
    startOffenseScore: number;
    startDefenseScore: number;
    endOffenseScore: number;
    endDefenseScore: number;
};

export type ExpandedTeamSRS = {
    year: number;
    team: string;
    conference: (string) | null;
    division: (string) | null;
    rating: number;
    ranking: (number) | null;
    classification: DivisionClassification;
};

export type FieldGoalEP = {
    yardsToGoal: number;
    distance: number;
    expectedPoints: number;
};

export type Game = {
    id: number;
    season: number;
    week: number;
    seasonType: SeasonType;
    startDate: string;
    startTimeTBD: boolean;
    completed: boolean;
    neutralSite: boolean;
    conferenceGame: boolean;
    attendance: (number) | null;
    venueId: (number) | null;
    venue: (string) | null;
    homeId: number;
    homeTeam: string;
    homeConference: (string) | null;
    homeClassification: ((DivisionClassification) | null);
    homePoints: (number) | null;
    homeLineScores: Array<(number)> | null;
    homePostgameWinProbability: (number) | null;
    homePregameElo: (number) | null;
    homePostgameElo: (number) | null;
    awayId: number;
    awayTeam: string;
    awayConference: (string) | null;
    awayClassification: ((DivisionClassification) | null);
    awayPoints: (number) | null;
    awayLineScores: Array<(number)> | null;
    awayPostgameWinProbability: (number) | null;
    awayPregameElo: (number) | null;
    awayPostgameElo: (number) | null;
    excitementIndex: (number) | null;
    highlights: (string) | null;
    notes: (string) | null;
    playoff: ((GamePlayoff) | null);
};

export type GameHavocStats = {
    gameId: number;
    season: number;
    seasonType: SeasonTypeDB;
    week: number;
    team: string;
    conference: (string) | null;
    opponent: string;
    opponentConference: (string) | null;
    offense: {
        dbHavocRate: number;
        frontSevenHavocRate: number;
        havocRate: number;
        dbHavocEvents: number;
        frontSevenHavocEvents: number;
        totalHavocEvents: number;
        totalPlays: number;
    };
    defense: {
        dbHavocRate: number;
        frontSevenHavocRate: number;
        havocRate: number;
        dbHavocEvents: number;
        frontSevenHavocEvents: number;
        totalHavocEvents: number;
        totalPlays: number;
    };
};

export type GameLine = {
    provider: string;
    spread: (number) | null;
    formattedSpread: string;
    spreadOpen: (number) | null;
    overUnder: (number) | null;
    overUnderOpen: (number) | null;
    homeMoneyline: (number) | null;
    awayMoneyline: (number) | null;
};

export type GameMedia = {
    id: number;
    season: number;
    week: number;
    seasonType: SeasonType;
    startTime: string;
    isStartTimeTBD: boolean;
    homeTeam: string;
    homeConference: (string) | null;
    awayTeam: string;
    awayConference: (string) | null;
    mediaType: MediaType;
    outlet: string;
};

export type GamePlayerStatCategories = {
    name: string;
    types: Array<GamePlayerStatTypes>;
};

export type GamePlayerStatPlayer = {
    id: string;
    name: string;
    stat: string;
};

export type GamePlayerStats = {
    id: number;
    teams: Array<GamePlayerStatsTeam>;
};

export type GamePlayerStatsTeam = {
    team: string;
    conference: (string) | null;
    homeAway: 'home' | 'away';
    points: (number) | null;
    categories: Array<GamePlayerStatCategories>;
};

export type homeAway = 'home' | 'away';

export type GamePlayerStatTypes = {
    name: string;
    athletes: Array<GamePlayerStatPlayer>;
};

export type GamePlayoff = {
    competition: PlayoffCompetition;
    format: string;
    round: PlayoffRound;
    roundName: string;
    bracketSlot: string;
    homeSeed: (number) | null;
    awaySeed: (number) | null;
    bowlName: (string) | null;
};

export type GameStatus = 'scheduled' | 'in_progress' | 'completed';

export type GameTeamStats = {
    id: number;
    teams: Array<GameTeamStatsTeam>;
};

export type GameTeamStatsTeam = {
    teamId: number;
    team: string;
    conference: (string) | null;
    homeAway: 'home' | 'away';
    points: (number) | null;
    stats: Array<GameTeamStatsTeamStat>;
};

export type GameTeamStatsTeamStat = {
    category: string;
    stat: string;
};

export type GameWeather = {
    id: number;
    season: number;
    week: number;
    seasonType: SeasonType;
    startTime: string;
    gameIndoors: boolean;
    homeTeam: string;
    homeConference: (string) | null;
    awayTeam: string;
    awayConference: (string) | null;
    venueId: number;
    venue: string;
    temperature: (number) | null;
    dewPoint: (number) | null;
    humidity: (number) | null;
    precipitation: (number) | null;
    snowfall: (number) | null;
    windDirection: (number) | null;
    windSpeed: (number) | null;
    pressure: (number) | null;
    weatherConditionCode: (number) | null;
    weatherCondition: (string) | null;
};

export type KickerPAAR = {
    year: number;
    athleteId: string;
    athleteName: string;
    team: string;
    conference: string;
    paar: number;
    attempts: number;
};

export type LiveGame = {
    id: number;
    status: string;
    period: (number) | null;
    clock: string;
    possession: string;
    down: (number) | null;
    distance: (number) | null;
    yardsToGoal: (number) | null;
    teams: Array<LiveGameTeam>;
    drives: Array<LiveGameDrive>;
};

export type LiveGameDrive = {
    id: string;
    offenseId: number;
    offense: string;
    defenseId: number;
    defense: string;
    playCount: number;
    yards: number;
    startPeriod: number;
    startClock: (string) | null;
    startYardsToGoal: number;
    endPeriod: (number) | null;
    endClock: (string) | null;
    endYardsToGoal: (number) | null;
    duration: (string) | null;
    scoringOpportunity: boolean;
    result: string;
    pointsGained: number;
    plays: Array<LiveGamePlay>;
};

export type LiveGamePlay = {
    id: string;
    homeScore: number;
    awayScore: number;
    period: number;
    clock: string;
    wallClock: string;
    teamId: number;
    team: string;
    down: number;
    distance: number;
    yardsToGoal: number;
    yardsGained: number;
    playTypeId: number;
    playType: string;
    epa: (number) | null;
    garbageTime: boolean;
    success: boolean;
    rushPass: 'rush' | 'pass' | 'other';
    downType: 'passing' | 'standard';
    playText: string;
};

export type rushPass = 'rush' | 'pass' | 'other';

export type downType = 'passing' | 'standard';

export type LiveGameTeam = {
    teamId: number;
    team: string;
    homeAway: 'home' | 'away';
    lineScores: Array<(number)>;
    points: number;
    drives: number;
    scoringOpportunities: number;
    pointsPerOpportunity: number;
    averageStartYardLine: (number) | null;
    plays: number;
    lineYards: number;
    lineYardsPerRush: number;
    secondLevelYards: number;
    secondLevelYardsPerRush: number;
    openFieldYards: number;
    openFieldYardsPerRush: number;
    epaPerPlay: number;
    totalEpa: number;
    passingEpa: number;
    epaPerPass: number;
    rushingEpa: number;
    epaPerRush: number;
    successRate: number;
    standardDownSuccessRate: number;
    passingDownSuccessRate: number;
    explosiveness: number;
    /**
     * Deserve-to-win metric for this team
     */
    deserveToWin?: number;
};

export type Matchup = {
    team1: string;
    team2: string;
    startYear?: number;
    endYear?: number;
    team1Wins: number;
    team2Wins: number;
    ties: number;
    games: Array<MatchupGame>;
};

export type MatchupGame = {
    season: number;
    week: number;
    seasonType: string;
    date: string;
    neutralSite: boolean;
    venue: (string) | null;
    homeTeam: string;
    homeScore: (number) | null;
    awayTeam: string;
    awayScore: (number) | null;
    winner: (string) | null;
};

export type MediaType = 'tv' | 'radio' | 'web' | 'ppv' | 'mobile';

export type Play = {
    id: string;
    driveId: string;
    gameId: number;
    driveNumber: (number) | null;
    playNumber: (number) | null;
    offense: string;
    offenseConference: (string) | null;
    offenseScore: number;
    defense: string;
    home: string;
    away: string;
    defenseConference: (string) | null;
    defenseScore: number;
    period: number;
    clock: {
        seconds: (number) | null;
        minutes: (number) | null;
    };
    offenseTimeouts: (number) | null;
    defenseTimeouts: (number) | null;
    yardline: number;
    yardsToGoal: number;
    down: number;
    distance: number;
    yardsGained: number;
    scoring: boolean;
    playType: string;
    playText: (string) | null;
    ppa: (number) | null;
    wallclock: (string) | null;
};

export type PlayerGamePredictedPointsAdded = {
    season: number;
    week: number;
    seasonType: SeasonType;
    id: string;
    name: string;
    position: string;
    team: string;
    opponent: string;
    averagePPA: {
        rush?: number;
        pass?: number;
        all: number;
    };
};

export type PlayerGameSuccessRate = {
    season: number;
    seasonType: SeasonTypeDB;
    week: number;
    gameId: number;
    id: string;
    name: string;
    position: string;
    team: string;
    conference: string;
    opponent: string;
    passing: PlayerSuccessRateSplit;
    rushing: PlayerSuccessRateSplit;
};

export type PlayerGameUsage = {
    total: number;
    quarter1: (number) | null;
    quarter2: (number) | null;
    quarter3: (number) | null;
    quarter4: (number) | null;
    rushing: number;
    passing: number;
    player: string;
    team: string;
    position: string;
};

export type PlayerPPA = {
    player: string;
    team: string;
    position: string;
    average: PlayerStatsByQuarter;
    cumulative: PlayerStatsByQuarter;
};

export type PlayerPPAChartItem = {
    playNumber: number;
    avgPPA: number;
};

export type PlayerSearchResult = {
    id: string;
    team: string;
    name: string;
    firstName: (string) | null;
    lastName: (string) | null;
    weight: (number) | null;
    height: (number) | null;
    jersey: (number) | null;
    position: string;
    hometown: string;
    teamColor: string;
    teamColorSecondary: string;
    activeStartYear: (number) | null;
    activeEndYear: (number) | null;
    teamStints: Array<PlayerSearchTeamStint>;
};

export type PlayerSearchTeamStint = {
    team: string;
    startYear: (number) | null;
    endYear: (number) | null;
};

export type PlayerSeasonOverview = {
    season: number;
    id: string;
    name: string;
    position: string;
    team: string;
    conference: string;
    games: number;
    boxScoreStats: {
        categories: Array<PlayerSeasonOverviewCategory>;
    };
    usage?: {
        passingDowns: (number) | null;
        standardDowns: (number) | null;
        thirdDown: (number) | null;
        secondDown: (number) | null;
        firstDown: (number) | null;
        rush: (number) | null;
        pass: (number) | null;
        overall: (number) | null;
    };
    ppa?: PlayerSeasonOverviewPPA;
};

export type PlayerSeasonOverviewCategory = {
    name: string;
    stats: Array<PlayerSeasonOverviewStat>;
};

export type PlayerSeasonOverviewPPA = {
    average: {
        passingDowns?: number;
        standardDowns?: number;
        thirdDown?: number;
        secondDown?: number;
        firstDown?: number;
        rush?: number;
        pass?: number;
        all: number;
    };
    total: {
        passingDowns?: number;
        standardDowns?: number;
        thirdDown?: number;
        secondDown?: number;
        firstDown?: number;
        rush?: number;
        pass?: number;
        all: number;
    };
};

export type PlayerSeasonOverviewStat = {
    name: string;
    value: string;
};

export type PlayerSeasonPredictedPointsAdded = {
    season: number;
    id: string;
    name: string;
    position: string;
    team: string;
    conference: string;
    averagePPA: {
        passingDowns?: number;
        standardDowns?: number;
        thirdDown?: number;
        secondDown?: number;
        firstDown?: number;
        rush?: number;
        pass?: number;
        all: number;
    };
    totalPPA: {
        passingDowns?: number;
        standardDowns?: number;
        thirdDown?: number;
        secondDown?: number;
        firstDown?: number;
        rush?: number;
        pass?: number;
        all: number;
    };
};

export type PlayerSeasonSuccessRate = {
    season: number;
    id: string;
    name: string;
    position: string;
    team: string;
    conference: string;
    passing: PlayerSuccessRateSplit;
    rushing: PlayerSuccessRateSplit;
};

export type PlayerStat = {
    season: number;
    playerId: string;
    player: string;
    position: string;
    team: string;
    conference: string;
    category: string;
    statType: string;
    stat: string;
};

export type PlayerStatsByQuarter = {
    total: number;
    quarter1: (number) | null;
    quarter2: (number) | null;
    quarter3: (number) | null;
    quarter4: (number) | null;
    rushing: number;
    passing: number;
};

export type PlayerSuccessRateSplit = {
    plays: number;
    successes: number;
    successRate: (number) | null;
};

export type PlayerTransfer = {
    season: number;
    firstName: string;
    lastName: string;
    position: string;
    origin: string;
    destination: (string) | null;
    transferDate: (string) | null;
    rating: (number) | null;
    stars: (number) | null;
    eligibility: ((TransferEligibility) | null);
};

export type PlayerUsage = {
    season: number;
    id: string;
    name: string;
    position: string;
    team: string;
    conference: string;
    usage: {
        passingDowns: (number) | null;
        standardDowns: (number) | null;
        thirdDown: (number) | null;
        secondDown: (number) | null;
        firstDown: (number) | null;
        rush: (number) | null;
        pass: (number) | null;
        overall: (number) | null;
    };
};

export type PlayerWeightedEPA = {
    year: number;
    athleteId: string;
    athleteName: string;
    position: string;
    team: string;
    conference: string;
    wepa: number;
    plays: number;
};

export type PlayoffAdvancement = {
    matchupId: number;
    bracketSlot: string;
    position: number;
};

export type PlayoffBidType = 'automatic' | 'at_large';

export type PlayoffCompetition = 'cfp';

export type PlayoffCompetition_Cfp = 'cfp';

export type PlayoffLinkedGame = {
    id: number;
    startDate: string;
    completed: boolean;
    homeTeam: PlayoffTeam;
    homePoints: (number) | null;
    awayTeam: PlayoffTeam;
    awayPoints: (number) | null;
    venueId: (number) | null;
    venue: (string) | null;
};

export type PlayoffMatchup = {
    id: number;
    bracketSlot: string;
    round: PlayoffRound;
    roundName: string;
    roundOrder: number;
    matchupOrder: number;
    startDate: (string) | null;
    bowlName: (string) | null;
    slots: Array<PlayoffMatchupSlot>;
    game: ((PlayoffLinkedGame) | null);
    advancesTo: ((PlayoffAdvancement) | null);
};

export type PlayoffMatchupSlot = {
    position: number;
    seed: (number) | null;
    participant: ((PlayoffTeam) | null);
    source: ((PlayoffMatchupSlotSource) | null);
};

export type PlayoffMatchupSlotSource = {
    matchupId: number;
    bracketSlot: string;
    outcome: 'winner';
};

export type outcome = 'winner';

export type PlayoffOutcome = 'active' | 'eliminated' | 'champion';

export type PlayoffParticipant = {
    team: PlayoffTeam;
    committeeRank: (number) | null;
    seed: number;
    bidType: PlayoffBidType;
    qualificationReason: (string) | null;
    conferenceChampion: boolean;
    qualifyingConference: (string) | null;
    firstRoundBye: boolean;
    outcome: PlayoffOutcome;
    eliminatedRound: ((PlayoffRound) | null);
};

export type PlayoffRound = 'first_round' | 'quarterfinal' | 'semifinal' | 'championship';

export type PlayoffRoundRecord = {
    code: PlayoffRound;
    name: string;
    order: number;
    matchups: Array<PlayoffMatchup>;
};

export type PlayoffStatus = 'scheduled' | 'selected' | 'in_progress' | 'completed';

export type PlayoffTeam = {
    id: number;
    school: string;
    conference: (string) | null;
};

export type PlayStat = {
    gameId: number;
    season: number;
    week: number;
    team: string;
    conference: string;
    opponent: string;
    teamScore: number;
    opponentScore: number;
    driveId: string;
    playId: string;
    period: number;
    clock: {
        seconds: (number) | null;
        minutes: (number) | null;
    };
    yardsToGoal: number;
    down: number;
    distance: number;
    athleteId: string;
    athleteName: string;
    statType: string;
    stat: number;
};

export type PlayStatType = {
    id: number;
    name: string;
};

export type PlayType = {
    id: number;
    text: string;
    abbreviation: (string) | null;
};

export type PlayWinProbability = {
    gameId: number;
    playId: string;
    playText: string;
    homeId: number;
    home: string;
    awayId: number;
    away: string;
    spread: number;
    homeBall: boolean;
    homeScore: number;
    awayScore: number;
    yardLine: number;
    down: number;
    distance: number;
    homeWinProbability: number;
    playNumber: number;
};

export type Poll = {
    poll: string;
    isFinal: (boolean) | null;
    ranks: Array<PollRank>;
};

export type PollRank = {
    rank: (number) | null;
    teamId: number;
    school: string;
    conference: (string) | null;
    firstPlaceVotes: (number) | null;
    points: (number) | null;
};

export type PollWeek = {
    season: number;
    seasonType: SeasonType;
    week: number;
    polls: Array<Poll>;
};

export type PredictedPointsValue = {
    yardLine: number;
    predictedPoints: number;
};

export type PregameWinProbability = {
    season: number;
    seasonType: SeasonType;
    week: number;
    gameId: number;
    homeTeam: string;
    awayTeam: string;
    spread: number;
    homeWinProbability: number;
};

export type RankingPoll = 'cfp';

export type Recruit = {
    id: string;
    athleteId: (string) | null;
    recruitType: RecruitClassification;
    year: number;
    ranking: (number) | null;
    name: string;
    school: (string) | null;
    committedTo: (string) | null;
    position: (string) | null;
    height: (number) | null;
    weight: (number) | null;
    stars: (number) | null;
    rating: (number) | null;
    city: (string) | null;
    stateProvince: (string) | null;
    country: (string) | null;
    hometownInfo: {
        fipsCode: (string) | null;
        longitude: (number) | null;
        latitude: (number) | null;
    };
};

export type RecruitClassification = 'JUCO' | 'PrepSchool' | 'HighSchool';

export type ReturningProduction = {
    season: number;
    team: string;
    conference: string;
    totalPPA: number;
    totalPassingPPA: number;
    totalReceivingPPA: number;
    totalRushingPPA: number;
    percentPPA: number;
    percentPassingPPA: number;
    percentReceivingPPA: number;
    percentRushingPPA: number;
    usage: number;
    passingUsage: number;
    receivingUsage: number;
    rushingUsage: number;
};

export type RosterPlayer = {
    id: string;
    firstName: string;
    lastName: string;
    team: string;
    height: (number) | null;
    weight: (number) | null;
    jersey: (number) | null;
    /**
     * @deprecated
     */
    year: number;
    position: (string) | null;
    homeCity: (string) | null;
    homeState: (string) | null;
    homeCountry: (string) | null;
    homeLatitude: (number) | null;
    homeLongitude: (number) | null;
    homeCountyFIPS: (string) | null;
    recruitIds: Array<(string)> | null;
};

export type ScoreboardGame = {
    id: number;
    startDate: string;
    startTimeTBD: boolean;
    tv: (string) | null;
    neutralSite: boolean;
    conferenceGame: boolean;
    status: GameStatus;
    period: (number) | null;
    clock: (string) | null;
    situation: (string) | null;
    possession: (string) | null;
    lastPlay: (string) | null;
    venue: {
        state: (string) | null;
        city: (string) | null;
        name: (string) | null;
    };
    homeTeam: {
        winProbability: (number) | null;
        lineScores: Array<(number)> | null;
        points: (number) | null;
        classification: ((DivisionClassification) | null);
        conference: (string) | null;
        name: string;
        id: number;
    };
    awayTeam: {
        winProbability: (number) | null;
        lineScores: Array<(number)> | null;
        points: (number) | null;
        classification: ((DivisionClassification) | null);
        conference: (string) | null;
        name: string;
        id: number;
    };
    weather: {
        windDirection: (number) | null;
        windSpeed: (number) | null;
        description: (string) | null;
        temperature: (number) | null;
    };
    betting: {
        awayMoneyline: (number) | null;
        homeMoneyline: (number) | null;
        overUnder: (number) | null;
        spread: (number) | null;
    };
};

export type SeasonType = 'regular' | 'postseason' | 'both' | 'allstar' | 'spring_regular' | 'spring_postseason';

export type SeasonTypeDB = 'allstar' | 'postseason' | 'preseason' | 'regular' | 'spring_postseason' | 'spring_regular';

export type StatsByQuarter = {
    total: number;
    quarter1: (number) | null;
    quarter2: (number) | null;
    quarter3: (number) | null;
    quarter4: (number) | null;
};

export type Team = {
    id: number;
    school: string;
    mascot: (string) | null;
    abbreviation: (string) | null;
    alternateNames: Array<(string)> | null;
    conference: (string) | null;
    division: (string) | null;
    classification: (string) | null;
    color: (string) | null;
    alternateColor: (string) | null;
    logos: Array<(string)> | null;
    twitter: (string) | null;
    location: ((Venue) | null);
};

export type TeamATS = {
    year: number;
    teamId: number;
    team: string;
    conference: (string) | null;
    games: number;
    atsWins: number;
    atsLosses: number;
    atsPushes: number;
    avgCoverMargin: (number) | null;
};

export type TeamConferenceAffiliation = {
    teamId: number;
    team: string;
    conferenceId: number;
    conference: string;
    conferenceAbbreviation: (string) | null;
    classification: ((ConferenceClassification) | null);
    conferenceDivision: (string) | null;
    startYear: number;
    endYear: (number) | null;
};

export type TeamConferenceChange = {
    teamId: number;
    team: string;
    fromConferenceId: number;
    fromConference: string;
    fromConferenceAbbreviation: (string) | null;
    fromClassification: ((ConferenceClassification) | null);
    toConferenceId: number;
    toConference: string;
    toConferenceAbbreviation: (string) | null;
    toClassification: ((ConferenceClassification) | null);
    effectiveYear: number;
};

export type TeamCoreRating = {
    year: number;
    throughSeasonType: CoreRatingSeasonType;
    throughWeek: number;
    team: string;
    conference: (string) | null;
    /**
     * Offense-minus-defense composite; higher is better.
     */
    overall: number;
    /**
     * Points created above average per 100 qualifying plays; higher is better.
     */
    offense: number;
    /**
     * Points allowed above average per 100 qualifying plays; lower is better.
     */
    defense: number;
    offensePlays: number;
    defensePlays: number;
    modelVersion: string;
};

export type TeamElo = {
    year: number;
    team: string;
    conference: string;
    elo: (number) | null;
};

export type TeamExplosiveness = {
    team: string;
    overall: StatsByQuarter;
};

export type TeamFieldPosition = {
    team: string;
    averageStart: number;
    averageStartingPredictedPoints: number;
};

export type TeamFPI = {
    year: number;
    team: string;
    conference: (string) | null;
    fpi: (number) | null;
    resumeRanks: {
        gameControl: (number) | null;
        remainingStrengthOfSchedule: (number) | null;
        strengthOfSchedule: (number) | null;
        averageWinProbability: (number) | null;
        fpi: (number) | null;
        strengthOfRecord: (number) | null;
    };
    efficiencies: {
        specialTeams: (number) | null;
        defense: (number) | null;
        offense: (number) | null;
        overall: (number) | null;
    };
};

export type TeamGamePredictedPointsAdded = {
    gameId: number;
    season: number;
    week: number;
    seasonType: SeasonType;
    team: string;
    conference: string;
    opponent: string;
    offense: {
        thirdDown: number;
        secondDown: number;
        firstDown: number;
        rushing: number;
        passing: number;
        overall: number;
    };
    defense: {
        thirdDown: number;
        secondDown: number;
        firstDown: number;
        rushing: number;
        passing: number;
        overall: number;
    };
};

export type TeamHavoc = {
    team: string;
    total: number;
    frontSeven: number;
    db: number;
};

export type TeamPPA = {
    team: string;
    plays: number;
    overall: StatsByQuarter;
    passing: StatsByQuarter;
    rushing: StatsByQuarter;
};

export type TeamRecord = {
    games: number;
    wins: number;
    losses: number;
    ties: number;
};

export type TeamRecords = {
    year: number;
    teamId: number;
    team: string;
    classification: ((DivisionClassification) | null);
    conference: string;
    division: string;
    expectedWins: (number) | null;
    total: TeamRecord;
    conferenceGames: TeamRecord;
    homeGames: TeamRecord;
    awayGames: TeamRecord;
    neutralSiteGames: TeamRecord;
    regularSeason: TeamRecord;
    postseason: TeamRecord;
};

export type TeamRecruitingRanking = {
    year: number;
    rank: number;
    team: string;
    points: number;
};

export type TeamRushingStats = {
    team: string;
    powerSuccess: number;
    stuffRate: number;
    lineYards: number;
    lineYardsAverage: number;
    secondLevelYards: number;
    secondLevelYardsAverage: number;
    openFieldYards: number;
    openFieldYardsAverage: number;
};

export type TeamScoringOpportunities = {
    team: string;
    opportunities: number;
    points: number;
    pointsPerOpportunity: number;
};

export type TeamSeasonPredictedPointsAdded = {
    season: number;
    conference: string;
    team: string;
    offense: {
        cumulative: {
            rushing: number;
            passing: number;
            total: number;
        };
        thirdDown: number;
        secondDown: number;
        firstDown: number;
        rushing: number;
        passing: number;
        overall: number;
    };
    defense: {
        cumulative: {
            rushing: number;
            passing: number;
            total: number;
        };
        thirdDown: number;
        secondDown: number;
        firstDown: number;
        rushing: number;
        passing: number;
        overall: number;
    };
};

export type TeamSP = {
    year: number;
    team: string;
    conference: (string) | null;
    rating: number;
    ranking: (number) | null;
    secondOrderWins: (number) | null;
    sos: (number) | null;
    offense: {
        pace: (number) | null;
        runRate: (number) | null;
        passingDowns: (number) | null;
        standardDowns: (number) | null;
        passing: (number) | null;
        rushing: (number) | null;
        explosiveness: (number) | null;
        success: (number) | null;
        rating: number;
        ranking: (number) | null;
    };
    defense: {
        havoc: {
            db: (number) | null;
            frontSeven: (number) | null;
            total: (number) | null;
        };
        passingDowns: (number) | null;
        standardDowns: (number) | null;
        passing: (number) | null;
        rushing: (number) | null;
        explosiveness: (number) | null;
        success: (number) | null;
        rating: number;
        ranking: (number) | null;
    };
    specialTeams: {
        rating: (number) | null;
    };
};

export type TeamSRS = {
    year: number;
    team: string;
    conference: (string) | null;
    division: (string) | null;
    rating: number;
    ranking: (number) | null;
};

export type TeamStat = {
    season: number;
    team: string;
    conference: string;
    statName: string;
    statValue: (string | number);
};

export type TeamSuccessRates = {
    team: string;
    overall: StatsByQuarter;
    standardDowns: StatsByQuarter;
    passingDowns: StatsByQuarter;
};

export type TeamTalent = {
    year: number;
    team: string;
    talent: number;
};

export type TransferEligibility = 'Withdrawn' | 'TBD' | 'PendingAppeal' | 'SittingOne' | 'Immediate';

export type UserFeatureAccess = {
    adjustedMetrics: boolean;
    weather: boolean;
    scoreboard: boolean;
    livePlayByPlay: boolean;
    graphQl: boolean;
};

export type UserInfo = {
    patronLevel: number;
    tierName: string;
    monthlyLimit: (number) | null;
    remainingCalls: (number) | null;
    usedCalls: (number) | null;
    resetAt: string;
    sharedPool: boolean;
    products: Array<(string)>;
    features: UserFeatureAccess;
};

export type UserUsage = {
    window: UserUsageWindow;
    api: UserUsageApi;
    totals: UserUsageTotals;
    topEndpoints: Array<UserUsageEndpoint>;
    recentRequests: Array<UserUsageRecentRequest>;
};

export type UserUsageApi = 'all' | 'cfb' | 'cbb';

export type UserUsageEndpoint = {
    api: UserUsageApi;
    endpoint: string;
    requests: number;
    lastUsedAt: string;
};

export type UserUsageRecentRequest = {
    api: UserUsageApi;
    endpoint: string;
    requestedAt: string;
};

export type UserUsageTotals = {
    requests: number;
    cfbRequests: number;
    cbbRequests: number;
    uniqueEndpoints: number;
};

export type UserUsageWindow = {
    start: string;
    end: string;
};

export type Venue = {
    id: (number) | null;
    name: (string) | null;
    city: (string) | null;
    state: (string) | null;
    zip: (string) | null;
    countryCode: (string) | null;
    timezone: (string) | null;
    latitude: (number) | null;
    longitude: (number) | null;
    elevation: (string) | null;
    capacity: (number) | null;
    constructionYear: (number) | null;
    grass?: (boolean) | null;
    dome?: (boolean) | null;
};

export type GetAdjustedTeamSeasonStatsData = {
    query?: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetAdjustedTeamSeasonStatsResponse = (Array<AdjustedTeamMetrics>);

export type GetAdjustedTeamSeasonStatsError = unknown;

export type GetAdjustedPlayerPassingStatsData = {
    query?: {
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Player position abbreviation.
         */
        position?: string;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetAdjustedPlayerPassingStatsResponse = (Array<PlayerWeightedEPA>);

export type GetAdjustedPlayerPassingStatsError = unknown;

export type GetAdjustedPlayerRushingStatsData = {
    query?: {
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Player position abbreviation.
         */
        position?: string;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetAdjustedPlayerRushingStatsResponse = (Array<PlayerWeightedEPA>);

export type GetAdjustedPlayerRushingStatsError = unknown;

export type GetKickerPaarData = {
    query?: {
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetKickerPaarResponse = (Array<KickerPAAR>);

export type GetKickerPaarError = unknown;

export type GetTeamsData = {
    query?: {
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Season year for historical conference affiliations.
         */
        year?: number;
    };
};

export type GetTeamsResponse = (Array<Team>);

export type GetTeamsError = unknown;

export type GetFbsTeamsData = {
    query?: {
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetFbsTeamsResponse = (Array<Team>);

export type GetFbsTeamsError = unknown;

export type GetMatchupData = {
    query: {
        /**
         * Latest season year to include.
         */
        maxYear?: number;
        /**
         * Earliest season year to include.
         */
        minYear?: number;
        /**
         * First team name.
         */
        team1: string;
        /**
         * Second team name.
         */
        team2: string;
    };
};

export type GetMatchupResponse = (Matchup);

export type GetMatchupError = unknown;

export type GetTeamsAtsData = {
    query: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetTeamsAtsResponse = (Array<TeamATS>);

export type GetTeamsAtsError = unknown;

export type GetRosterData = {
    query?: {
        /**
         * Division classification: `fbs` or `fcs`.
         */
        classification?: DivisionClassification;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year. Defaults to 2025.
         */
        year?: number;
    };
};

export type GetRosterResponse = (Array<RosterPlayer>);

export type GetRosterError = unknown;

export type GetConferencesData = {
    query?: {
        /**
         * Conference classification.
         */
        classification?: ConferenceClassification;
        /**
         * Season year used to calculate membership.
         */
        year?: number;
    };
};

export type GetConferencesResponse = (Array<Conference>);

export type GetConferencesError = unknown;

export type GetTeamConferenceChangesData = {
    query: {
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetTeamConferenceChangesResponse = (Array<TeamConferenceChange>);

export type GetTeamConferenceChangesError = unknown;

export type GetTeamConferenceAffiliationsData = {
    query?: {
        /**
         * Conference classification.
         */
        classification?: ConferenceClassification;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Latest season year to include.
         */
        maxYear?: number;
        /**
         * Earliest season year to include.
         */
        minYear?: number;
        /**
         * Team school name or abbreviation.
         */
        team?: string;
        /**
         * Season year. Cannot be combined with `minYear` or `maxYear`.
         */
        year?: number;
    };
};

export type GetTeamConferenceAffiliationsResponse = (Array<TeamConferenceAffiliation>);

export type GetTeamConferenceAffiliationsError = unknown;

export type GetTalentData = {
    query: {
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetTalentResponse = (Array<TeamTalent>);

export type GetTalentError = unknown;

export type GetVenuesResponse = (Array<Venue>);

export type GetVenuesError = unknown;

export type GetPlayerSeasonStatsData = {
    query: {
        /**
         * Statistical category.
         */
        category?: string;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Latest week to include.
         */
        endWeek?: number;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Earliest week to include.
         */
        startWeek?: number;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetPlayerSeasonStatsResponse = (Array<PlayerStat>);

export type GetPlayerSeasonStatsError = unknown;

export type GetPlayerSeasonSuccessRatesData = {
    query?: {
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Latest week to include.
         */
        endWeek?: number;
        /**
         * Excludes garbage-time plays when `true`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Player ID. Required unless `year` is specified.
         */
        playerId?: number;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Earliest week to include.
         */
        startWeek?: number;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Minimum credited passing and rushing plays.
         */
        threshold?: number;
        /**
         * Season year. Required unless `playerId` is specified.
         */
        year?: number;
    };
};

export type GetPlayerSeasonSuccessRatesResponse = (Array<PlayerSeasonSuccessRate>);

export type GetPlayerSeasonSuccessRatesError = unknown;

export type GetPlayerGameSuccessRatesData = {
    query: {
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Excludes garbage-time plays when `true`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Player ID.
         */
        playerId?: number;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Minimum credited passing and rushing plays.
         */
        threshold?: number;
        /**
         * Week number. Required unless `team` or `playerId` is specified.
         */
        week?: number;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetPlayerGameSuccessRatesResponse = (Array<PlayerGameSuccessRate>);

export type GetPlayerGameSuccessRatesError = unknown;

export type GetTeamStatsData = {
    query?: {
        /**
         * Division classification. Defaults to `fbs`.
         */
        classification?: DivisionClassification;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Latest week to include.
         */
        endWeek?: number;
        /**
         * Earliest week to include.
         */
        startWeek?: number;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetTeamStatsResponse = (Array<TeamStat>);

export type GetTeamStatsError = unknown;

export type GetCategoriesResponse = (Array<(string)>);

export type GetCategoriesError = unknown;

export type GetAdvancedSeasonStatsData = {
    query?: {
        /**
         * Division classification. Defaults to `fbs`.
         */
        classification?: DivisionClassification;
        /**
         * Latest week to include.
         */
        endWeek?: number;
        /**
         * Excludes garbage-time plays when `true`. Defaults
         * to `false`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Earliest week to include.
         */
        startWeek?: number;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetAdvancedSeasonStatsResponse = (Array<AdvancedSeasonStat>);

export type GetAdvancedSeasonStatsError = unknown;

export type GetAdvancedGameStatsData = {
    query?: {
        /**
         * Excludes garbage-time plays when `true`. Defaults
         * to `false`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Opponent team name.
         */
        opponent?: string;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetAdvancedGameStatsResponse = (Array<AdvancedGameStat>);

export type GetAdvancedGameStatsError = unknown;

export type GetGameHavocStatsData = {
    query?: {
        /**
         * Opponent team name.
         */
        opponent?: string;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetGameHavocStatsResponse = (Array<GameHavocStats>);

export type GetGameHavocStatsError = unknown;

export type GetRecruitsData = {
    query?: {
        /**
         * Recruit classification. Defaults to `HighSchool`.
         */
        classification?: RecruitClassification;
        /**
         * Position category.
         */
        position?: string;
        /**
         * State or province abbreviation.
         */
        state?: string;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Recruiting class year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetRecruitsResponse = (Array<Recruit>);

export type GetRecruitsError = unknown;

export type GetTeamRecruitingRankingsData = {
    query?: {
        /**
         * Team name.
         */
        team?: string;
        /**
         * Recruiting class year.
         */
        year?: number;
    };
};

export type GetTeamRecruitingRankingsResponse = (Array<TeamRecruitingRanking>);

export type GetTeamRecruitingRankingsError = unknown;

export type GetAggregatedTeamRecruitingRatingsData = {
    query?: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Latest recruiting class year. Defaults to the current year.
         */
        endYear?: number;
        /**
         * Recruit classification. Defaults to `HighSchool`.
         */
        recruitType?: RecruitClassification;
        /**
         * Earliest recruiting class year. Defaults to 2000.
         */
        startYear?: number;
        /**
         * Team name.
         */
        team?: string;
    };
};

export type GetAggregatedTeamRecruitingRatingsResponse = (Array<AggregatedTeamRecruiting>);

export type GetAggregatedTeamRecruitingRatingsError = unknown;

export type GetCoreData = {
    query?: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Exact team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetCoreResponse = (Array<TeamCoreRating>);

export type GetCoreError = unknown;

export type GetSpData = {
    query?: {
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetSpResponse = (Array<TeamSP>);

export type GetSpError = unknown;

export type GetConferenceSpData = {
    query?: {
        /**
         * Division classification. Defaults to `fbs`.
         */
        classification?: DivisionClassification;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetConferenceSpResponse = (Array<ConferenceSP>);

export type GetConferenceSpError = unknown;

export type GetSrsData = {
    query?: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetSrsResponse = (Array<TeamSRS>);

export type GetSrsError = unknown;

export type GetExpandedSrsData = {
    query?: {
        /**
         * Division classification: `fbs` or `fcs`.
         */
        classification?: DivisionClassification;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetExpandedSrsResponse = (Array<ExpandedTeamSRS>);

export type GetExpandedSrsError = unknown;

export type GetEloData = {
    query?: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Week number. Defaults to the latest available week in the
         * season.
         */
        week?: number;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetEloResponse = (Array<TeamElo>);

export type GetEloError = unknown;

export type GetFpiData = {
    query?: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetFpiResponse = (Array<TeamFPI>);

export type GetFpiError = unknown;

export type GetRankingsData = {
    query: {
        /**
         * Returns the CFP snapshot marked as final when `true`. Requires
         * `poll=cfp` and cannot be combined with `latest`.
         */
        final?: boolean;
        /**
         * Returns the latest CFP snapshot when `true`, preferring the
         * snapshot marked as final. Requires `poll=cfp` and cannot be combined with
         * `final`.
         */
        latest?: boolean;
        /**
         * Poll name.
         */
        poll?: RankingPoll;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Poll week.
         */
        week?: number;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetRankingsResponse = (Array<PollWeek>);

export type GetRankingsError = ({
    message: string;
});

export type GetPlaysData = {
    query: {
        /**
         * Division classification of either team.
         */
        classification?: DivisionClassification;
        /**
         * Conference of either team.
         */
        conference?: string;
        /**
         * Defensive team name.
         */
        defense?: string;
        /**
         * Defensive team conference.
         */
        defenseConference?: string;
        /**
         * Offensive team name.
         */
        offense?: string;
        /**
         * Offensive team conference.
         */
        offenseConference?: string;
        /**
         * Play type abbreviation.
         */
        playType?: string;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name on either side of the play.
         */
        team?: string;
        /**
         * Week number.
         */
        week: number;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetPlaysResponse = (Array<Play>);

export type GetPlaysError = unknown;

export type GetPlayTypesResponse = (Array<PlayType>);

export type GetPlayTypesError = unknown;

export type GetPlayStatsData = {
    query?: {
        /**
         * Athlete ID.
         */
        athleteId?: number;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Game ID.
         */
        gameId?: number;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Play stat type ID.
         */
        statTypeId?: number;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetPlayStatsResponse = (Array<PlayStat>);

export type GetPlayStatsError = unknown;

export type GetPlayStatTypesResponse = (Array<PlayStatType>);

export type GetPlayStatTypesError = unknown;

export type GetCfpPlayoffData = {
    query: {
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetCfpPlayoffResponse = (CfpPlayoff);

export type GetCfpPlayoffError = ({
    message: string;
} | CfpPlayoffNotFound);

export type GetCfpParticipantsData = {
    query: {
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetCfpParticipantsResponse = (Array<PlayoffParticipant>);

export type GetCfpParticipantsError = ({
    message: string;
} | CfpPlayoffNotFound);

export type GetCfpGamesData = {
    query: {
        /**
         * Playoff round.
         */
        round?: PlayoffRound;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetCfpGamesResponse = (Array<PlayoffMatchup>);

export type GetCfpGamesError = ({
    message: string;
} | CfpPlayoffNotFound);

export type SearchPlayersData = {
    query: {
        /**
         * Player position abbreviation.
         */
        position?: string;
        /**
         * Full or partial player name.
         */
        searchTerm: string;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type SearchPlayersResponse = (Array<PlayerSearchResult>);

export type SearchPlayersError = unknown;

export type GetPlayerUsageData = {
    query: {
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Excludes garbage-time plays when `true`. Defaults
         * to `false`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Player ID.
         */
        playerId?: number;
        /**
         * Player position abbreviation.
         */
        position?: string;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetPlayerUsageResponse = (Array<PlayerUsage>);

export type GetPlayerUsageError = unknown;

export type GetPlayerSeasonOverviewData = {
    query: {
        /**
         * Player ID.
         */
        playerId: number;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetPlayerSeasonOverviewResponse = (PlayerSeasonOverview);

export type GetPlayerSeasonOverviewError = unknown;

export type GetReturningProductionData = {
    query?: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetReturningProductionResponse = (Array<ReturningProduction>);

export type GetReturningProductionError = unknown;

export type GetTransferPortalData = {
    query: {
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetTransferPortalResponse = (Array<PlayerTransfer>);

export type GetTransferPortalError = unknown;

export type GetPredictedPointsData = {
    query: {
        /**
         * Distance to gain, in yards.
         */
        distance: number;
        /**
         * Down number.
         */
        down: number;
    };
};

export type GetPredictedPointsResponse = (Array<PredictedPointsValue>);

export type GetPredictedPointsError = unknown;

export type GetPredictedPointsAddedByTeamData = {
    query?: {
        /**
         * Division classification. Defaults to `fbs`.
         */
        classification?: DivisionClassification;
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Excludes garbage-time plays when `true`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetPredictedPointsAddedByTeamResponse = (Array<TeamSeasonPredictedPointsAdded>);

export type GetPredictedPointsAddedByTeamError = unknown;

export type GetPredictedPointsAddedByGameData = {
    query: {
        /**
         * Division classification. Defaults to `fbs`.
         */
        classification?: DivisionClassification;
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Excludes garbage-time plays when `true`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetPredictedPointsAddedByGameResponse = (Array<TeamGamePredictedPointsAdded>);

export type GetPredictedPointsAddedByGameError = unknown;

export type GetPredictedPointsAddedByPlayerGameData = {
    query: {
        /**
         * Excludes garbage-time plays when `true`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Player ID.
         */
        playerId?: string;
        /**
         * Player position abbreviation.
         */
        position?: string;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name. Required unless `week` is specified.
         */
        team?: string;
        /**
         * Minimum number of plays.
         */
        threshold?: number;
        /**
         * Week number. Required unless `team` is specified.
         */
        week?: number;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetPredictedPointsAddedByPlayerGameResponse = (Array<PlayerGamePredictedPointsAdded>);

export type GetPredictedPointsAddedByPlayerGameError = unknown;

export type GetPredictedPointsAddedByPlayerSeasonData = {
    query?: {
        /**
         * Conference abbreviation.
         */
        conference?: string;
        /**
         * Excludes garbage-time plays when `true`.
         */
        excludeGarbageTime?: boolean;
        /**
         * Player ID. Required unless `year` is specified.
         */
        playerId?: string;
        /**
         * Player position abbreviation.
         */
        position?: string;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Minimum number of plays.
         */
        threshold?: number;
        /**
         * Season year. Required unless `playerId` is specified.
         */
        year?: number;
    };
};

export type GetPredictedPointsAddedByPlayerSeasonResponse = (Array<PlayerSeasonPredictedPointsAdded>);

export type GetPredictedPointsAddedByPlayerSeasonError = unknown;

export type GetWinProbabilityData = {
    query: {
        /**
         * Game ID.
         */
        gameId: number;
    };
};

export type GetWinProbabilityResponse = (Array<PlayWinProbability>);

export type GetWinProbabilityError = unknown;

export type GetPregameWinProbabilitiesData = {
    query?: {
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetPregameWinProbabilitiesResponse = (Array<PregameWinProbability>);

export type GetPregameWinProbabilitiesError = unknown;

export type GetFieldGoalExpectedPointsResponse = (Array<FieldGoalEP>);

export type GetFieldGoalExpectedPointsError = unknown;

export type GetLivePlaysData = {
    query: {
        /**
         * Game ID.
         */
        gameId: number;
    };
};

export type GetLivePlaysResponse = (LiveGame);

export type GetLivePlaysError = unknown;

export type GetLinesData = {
    query?: {
        /**
         * Away team name.
         */
        away?: string;
        /**
         * Conference of either team.
         */
        conference?: string;
        /**
         * Game ID.
         */
        gameId?: number;
        /**
         * Home team name.
         */
        home?: string;
        /**
         * Betting line provider.
         */
        provider?: string;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name on either side of the game.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year. Required unless `gameId` is specified.
         */
        year?: number;
    };
};

export type GetLinesResponse = (Array<BettingGame>);

export type GetLinesError = unknown;

export type GetUserInfoResponse = (((UserInfo) | null));

export type GetUserInfoError = unknown;

export type GetUsageData = {
    query?: {
        /**
         * API to include: `all`, `cfb`, or `cbb`.
         */
        api?: UserUsageApi;
        /**
         * Trailing days to include. Defaults to 7; maximum 31.
         */
        days?: number;
        /**
         * Maximum endpoint and request rows to return. Defaults to 10;
         * maximum 50.
         */
        limit?: number;
    };
};

export type GetUsageResponse = (((UserUsage) | null));

export type GetUsageError = unknown;

export type GetGamesData = {
    query?: {
        /**
         * Away team name.
         */
        away?: string;
        /**
         * Division classification.
         */
        classification?: DivisionClassification;
        /**
         * Playoff competition.
         */
        competition?: PlayoffCompetition;
        /**
         * Conference of either team.
         */
        conference?: string;
        /**
         * Home team name.
         */
        home?: string;
        /**
         * Game ID. When specified, returns data for that game.
         */
        id?: number;
        /**
         * Playoff round. Requires `competition`.
         */
        round?: PlayoffRound;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name on either side of the game.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year. Required unless `id` is specified.
         */
        year?: number;
    };
};

export type GetGamesResponse = (Array<Game>);

export type GetGamesError = ({
    message: string;
});

export type GetGameTeamStatsData = {
    query?: {
        /**
         * Division classification.
         */
        classification?: DivisionClassification;
        /**
         * Conference name or abbreviation. One of `week`, `team`,
         * or `conference` is required when filtering by year.
         */
        conference?: string;
        /**
         * Game ID. When specified, returns statistics for that game.
         */
        id?: number;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name. One of `week`, `team`, or `conference` is required
         * when filtering by year.
         */
        team?: string;
        /**
         * Week number. One of `week`, `team`, or `conference` is required
         * when filtering by year.
         */
        week?: number;
        /**
         * Season year. Required unless `id` is specified.
         */
        year?: number;
    };
};

export type GetGameTeamStatsResponse = (Array<GameTeamStats>);

export type GetGameTeamStatsError = unknown;

export type GetGamePlayerStatsData = {
    query?: {
        /**
         * Player statistical category.
         */
        category?: string;
        /**
         * Division classification.
         */
        classification?: DivisionClassification;
        /**
         * Conference name or abbreviation. One of `week`, `team`,
         * or `conference` is required when filtering by year.
         */
        conference?: string;
        /**
         * Game ID. When specified, returns statistics for that game.
         */
        id?: number;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name. One of `week`, `team`, or `conference` is required
         * when filtering by year.
         */
        team?: string;
        /**
         * Week number. One of `week`, `team`, or `conference` is required
         * when filtering by year.
         */
        week?: number;
        /**
         * Season year. Required unless `id` is specified.
         */
        year?: number;
    };
};

export type GetGamePlayerStatsResponse = (Array<GamePlayerStats>);

export type GetGamePlayerStatsError = unknown;

export type GetMediaData = {
    query: {
        /**
         * Division classification.
         */
        classification?: DivisionClassification;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Media type.
         */
        mediaType?: MediaType;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetMediaResponse = (Array<GameMedia>);

export type GetMediaError = unknown;

export type GetWeatherData = {
    query?: {
        /**
         * Division classification.
         */
        classification?: DivisionClassification;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Game ID. When specified, returns weather for that game.
         */
        gameId?: number;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year. Required unless `gameId` is specified.
         */
        year?: number;
    };
};

export type GetWeatherResponse = (Array<GameWeather>);

export type GetWeatherError = unknown;

export type GetRecordsData = {
    query?: {
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
        /**
         * Team name. Required unless `year` is specified.
         */
        team?: string;
        /**
         * Season year. Required unless `team` is specified.
         */
        year?: number;
    };
};

export type GetRecordsResponse = (Array<TeamRecords>);

export type GetRecordsError = unknown;

export type GetCalendarData = {
    query: {
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetCalendarResponse = (Array<CalendarWeek>);

export type GetCalendarError = unknown;

export type GetScoreboardData = {
    query?: {
        /**
         * Division classification. Defaults to `fbs`.
         */
        classification?: DivisionClassification;
        /**
         * Conference name or abbreviation.
         */
        conference?: string;
    };
};

export type GetScoreboardResponse = (Array<ScoreboardGame>);

export type GetScoreboardError = unknown;

export type GetDrivesData = {
    query: {
        /**
         * Division classification of either team.
         */
        classification?: DivisionClassification;
        /**
         * Conference of either team.
         */
        conference?: string;
        /**
         * Defensive team name.
         */
        defense?: string;
        /**
         * Defensive team conference.
         */
        defenseConference?: string;
        /**
         * Offensive team name.
         */
        offense?: string;
        /**
         * Offensive team conference.
         */
        offenseConference?: string;
        /**
         * Season type.
         */
        seasonType?: SeasonType;
        /**
         * Team name on either side of the drive.
         */
        team?: string;
        /**
         * Week number.
         */
        week?: number;
        /**
         * Season year.
         */
        year: number;
    };
};

export type GetDrivesResponse = (Array<Drive>);

export type GetDrivesError = unknown;

export type GetDraftTeamsResponse = (Array<DraftTeam>);

export type GetDraftTeamsError = unknown;

export type GetDraftPositionsResponse = (Array<DraftPosition>);

export type GetDraftPositionsError = unknown;

export type GetDraftPicksData = {
    query?: {
        /**
         * College conference name or abbreviation.
         */
        conference?: string;
        /**
         * Position category.
         */
        position?: string;
        /**
         * College team name.
         */
        school?: string;
        /**
         * NFL team name.
         */
        team?: string;
        /**
         * Draft year.
         */
        year?: number;
    };
};

export type GetDraftPicksResponse = (Array<DraftPick>);

export type GetDraftPicksError = unknown;

export type GetCoachesData = {
    query?: {
        /**
         * Coach first name.
         */
        firstName?: string;
        /**
         * Coach last name.
         */
        lastName?: string;
        /**
         * Latest season year to include.
         */
        maxYear?: number;
        /**
         * Earliest season year to include.
         */
        minYear?: number;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year.
         */
        year?: number;
    };
};

export type GetCoachesResponse = (Array<Coach>);

export type GetCoachesError = unknown;

export type GetCoachProfileData = {
    query: {
        /**
         * Coach ID.
         */
        coachId: number;
    };
};

export type GetCoachProfileResponse = (CoachProfile);

export type GetCoachProfileError = ({
    message: string;
} | CoachNotFound);

export type GetCoachSeasonsData = {
    query?: {
        /**
         * Coach ID.
         */
        coachId?: number;
        /**
         * Latest season year to include.
         */
        maxYear?: number;
        /**
         * Earliest season year to include.
         */
        minYear?: number;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Exact season year.
         */
        year?: number;
    };
};

export type GetCoachSeasonsResponse = (Array<DetailedCoachSeason>);

export type GetCoachSeasonsError = ({
    message: string;
});

export type GetCoachTenuresData = {
    query?: {
        /**
         * Filters by active status when specified.
         */
        active?: boolean;
        /**
         * Coach ID.
         */
        coachId?: number;
        /**
         * Team name.
         */
        team?: string;
        /**
         * Season year contained within the tenure.
         */
        year?: number;
    };
};

export type GetCoachTenuresResponse = (Array<CoachTenure>);

export type GetCoachTenuresError = ({
    message: string;
});

export type GetAdvancedBoxScoreData = {
    query: {
        /**
         * Game ID.
         */
        id: number;
    };
};

export type GetAdvancedBoxScoreResponse = (AdvancedBoxScore);

export type GetAdvancedBoxScoreError = unknown;